name: Run tests and lint

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Testing
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Linting
        run: npm run lint