name: Running tests and linter
on: pull_request:
      branches:
        - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: installing deps
        run: npm ci
      - name: testing
        run: npm run test
      - name: Check Jest test results
        run: |
          if npm test | grep -q "Test Suites: 0 passed"; then
            echo "Jest tests failed. Exiting."
            exit 1
          else
            echo "Jest tests passed. Continuing."
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: installing deps
        run: npm ci
      - name: linting
        run: npm run lint